COMMIT_VERSION: 'f1b69735'
ACR_NAME: 'bjd145'
KEYVAULT_NAME: 'pup-22205-kv'
AZURESQL_NAME: 'pup-22205-sql'
CLUSTER_NAME: 'pup-22205-aks'
NAMESPACE: 'default'
ARM_WORKLOAD_APP_ID: ''
ARM_TENANT_ID: ''
