FROM mcr.microsoft.com/dotnet/sdk:6.0 AS builder

WORKDIR /src/
COPY . .
RUN dotnet restore 
RUN dotnet publish -c Release --nologo -o publish/linux

#Build runtime image
FROM mcr.microsoft.com/dotnet/runtime-deps:6.0
RUN apk add --no-cache gcompat 

WORKDIR /app
COPY --from=builder /src/publish/linux/todoapi .
COPY appsettings.json .
EXPOSE 8443
ENTRYPOINT ["/app/todoapi"]
