name: Todo Api Build
on:
  schedule:
    - cron: "05 7 * * wed"
  workflow_dispatch:
  push:
    branches: 
    - main
    paths: 
    - './workload-identities/src/*'

permissions:
  id-token: write # Require write permission to Fetch an OIDC token.

jobs:
  buildImage:
    permissions:
      contents: read
      id-token: write
    runs-on: ubuntu-latest
    env:
      CONTAINER_NAME: todoapi

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v3

      - uses: azure/login@v2
        name: Azure login
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}

      - name: Build and push image to ACR
        run: az acr build --image ${{ env.CONTAINER_NAME }}:${{ github.sha }} --registry ${{ secrets.ACR_NAME }} -g ${{ secrets.ACR_RESOURCE_GROUP }} -f ./workload-identities/src/dockerfile ./workload-identities/src/
